# MySQL 连接信息
[mysql]
host = "127.0.0.1"
port = "3306"
username = "root"
password = "myPasswordForMySQL"
database = "wordpress"

# Excel
[excel]
file_name = "OneNav 导航站数据集.xlsx"
sites_sheet = "网址"
spare_links_sheet = "备用链接地址（其他站点）"

# 同步模式
[sync]
# part: 仅添加 wp_postmeta 中有 _sync_site_id 标记的网址（推荐）
# full: 强制保持数据一致，任何在 Excel 中没有的网址都会被删除（不推荐）
mode = "part"

# 导航站信息
[onenav]
# 域名
domain = "https://steam.cash"
# 【暂不支持更改】固定链接设置
permalink = "https://steam.cash/%post_id%.html"

# 单元测试
[test]
file_name = "OneNav 导航站数据集.xlsx"
sites_sheet = "测试网址"
spare_links_sheet = "测试备用链接地址（其他站点）"